name: Latest blog post workflow - medium
on:
  schedule: # Run workflow automatically
    - cron: '0 8 * * *' # Runs 8:00am, daily
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts from Medium
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@mr.sean.ryan"
          comment_tag_name: BLOG-POST-LIST-MEDIUM
          max_post_count: 8
